start_date = '2000-08-11'
end_date = '2022-12-31'

fee = 0.006 # i.e. 0.6 %
fee_coef = 1 - fee

support_sell_coef = 0.8
resistance_buy_coef = 1
fall_security_days = 30

target_percent_increase = 0.10
target_days = 15
target_feature = 'target'
target_feature_class = 'target_class'

support_column = 'support1'
resistance_column = 'resistance2'

stats = [
    'change',
    'rsi', 'rsi_6',
    'log-ret',
    'ups_10_c', 'downs_10_c',
    'close_-2~0_min', 'close_-2~0_max', 'close_-10~0_min', 'close_-10~0_max',
    'stochrsi', 'stochrsi_6',
    'wt1', 'wt2',
    'trix', 'middle_10_trix',
    'tema', 'middle_10_tema',
    'vr', 'vr_6',
    'wr', 'wr_6',
    'cci', 'cci_6',
    'atr', 'atr_5',
    'supertrend', 'supertrend_ub', 'supertrend_lb',
    'dma',
    'pdi', 'mdi', 'dx', 'adx', 'adxr',
    #'cr', 'cr-ma1', 'cr-ma2', 'cr-ma3',
    'middle',
    'boll', 'boll_ub', 'boll_lb',
    'macd', 'macds', 'macdh',
    'ppo', 'ppos', 'ppoh',
    'vwma', 'vwma_6',
    'chop', 'chop_6',
    'mfi', 'mfi_6',
]

X_features = [
    'day',
    'change', 'change_-10~0_min', 'change_-10~0_max',
    'rsi', 'rsi_6',
    'log-ret',
    'ups_10_c', 'downs_10_c',
    'close_-2~0_min', 'close_-2~0_max',
    'stochrsi', 'stochrsi_6',
    'wt1', 'wt2',
    'trix', 'middle_10_trix',
    'tema', 'middle_10_tema',
    # 'vr', 'vr_6',
    'wr', 'wr_6',
    'cci', 'cci_6',
    'atr', 'atr_5',
    'supertrend', 'supertrend_ub', 'supertrend_lb',
    'dma',
    'pdi', 'mdi', 'dx', 'adx', 'adxr',
    'middle',
    'boll', 'boll_ub', 'boll_lb',
    'macd', 'macds', 'macdh',
    'ppo', 'ppos', 'ppoh',
    'vwma', 'vwma_6',
    'chop', 'chop_6',
    'mfi', 'mfi_6',
]

tickers = [
    "^FCHI",
    "AB.PA",
    "A2A.MI",
    "ABCA.PA",
    "ABNX.PA",
    "ABVX.PA",
    "AC.PA",
    "ADP.PA",
    "AIR.PA",
    "AF.PA",
    "AI.PA",
    "AKW.PA",
    "ALBIO.PA",
    "ALD.PA",
    "ALO.PA",
    "ALTA.PA",
    "ATE.PA",
    "AMUN.PA",
    "APAM.AS",
    "MT",
    "ARG.PA",
    "AKE.PA",
    "PRC.PA",
    "ALATA.PA",
    "ATO.PA",
    "AVT.PA",
    "CS.PA",
    "BALYO.PA",
    "BAMI.MI",
    "BPE.MI",
    "BASS.PA",
    "BLC.PA",
    "BEN.PA",
    "BB.PA",
    "BIG.PA",
    "BIM.PA",
    "BNP.PA",
    "BOL.PA",
    "BON.PA",
    "EN.PA",
    "BVI.PA",
    "CAP.PA",
    "CARM.PA",
    "CA.PA",
    "CO.PA",
    "CATG.PA",
    "ALCLS.PA",
    "CGG.PA",
    "CRI.PA",
    "COFA.PA",
    "RE.PA",
    "CDA.PA",
    "CLA.PA",
    "COV.PA",
    "ACA.PA",
    "BN.PA",
    "AM.PA",
    "DSY.PA",
    "DBV.PA",
    "DBG.PA",
    "EDEN.PA",
    "EDF.PA",
    "FGR.PA",
    "EKI.PA",
    "ELIOR.PA",
    "ELIS.PA",
    "ENEL.MI",
    "ENGI.PA",
    "ENI.MI",
    "ERA.PA",
    "ERYP.PA",
    "EL.PA",
    "RF.PA",
    "ERF.PA",
    "ENX.PA",
    "EUCAR.PA",
    "ETL.PA",
    "EO.PA",
    "FDJ.PA",
    "FALG.PA",
    "FNAC.PA",
    "ALFPC.PA",
    "GFC.PA",
    "GNE.PA",
    "GNFT.PA",
    "GV.PA",
    "SIGHT.PA",
    "GET.PA",
    "GLO.PA",
    "2G3.SG",
    "GTT.PA",
    "GUI.PA",
    "RMS.PA",
    "ALHEX.PA",
    "HOLN.PA",
    "ICAD.PA",
    "IDL.PA",
    "NK.PA",
    "IPH.PA",
    "ITP.PA",
    "IVA.PA",
    "IPN.PA",
    "IPS.PA",
    "ISP.MI",
    "JCQ.PA",
    "DEC.PA",
    "JUVE.MI",
    "KOF.PA",
    "KER.PA",
    "LI.PA",
    "KORI.PA",
    "OR.PA",
    "MMB.PA",
    "LR.PA",
    "LNA.PA",
    "FII.PA",
    "MC.PA",
    "MMT.PA",
    "MDM.PA",
    "MTU.PA",
    "MAU.PA",
    "MCPHY.PA",
    "MEDCL.PA",
    "MERY.PA",
    "MRN.PA",
    "METEX.PA",
    "ML.PA",
    "NACON.PA",
    "NANO.PA",
    "NAVYA.PA",
    "NEOEN.PA",
    "NEX.PA",
    "NXI.PA",
    "COX.PA",
    "NOKIA.PA",
    "ORA.PA",
    "ORP.PA",
    "OSE.PA",
    "RI.PA",
    "PEUG.PA",
    "PHA.PA",
    "VAC.PA",
    "POM.PA",
    "PVL.PA",
    "POXEL.PA",
    "PWG.PA",
    "PUB.PA",
    "QDT.PA",
    "RCO.PA",
    "RNO.PA",
    "RXL.PA",
    "RN.MI",
    "RUI.PA",
    "SAF.PA",
    "SGO.PA",
    "SAN.PA",
    "SPM.MI",
    "SRS.MI",
    "DIM.PA",
    "SU.PA",
    "SCR.PA",
    "SK.PA",
    "SCHP.PA",
    "SEFER.PA",
    "SESG.PA",
    "SRP.PA",
    "SMCP.PA",
    "SII.PA",
    "GLE.PA",
    "SW.PA",
    "SOI.PA",
    "LOCAL.PA",
    "S30.PA",
    "SOLB.BR",
    "SOP.PA",
    "SPIE.PA",
    "SRG.MI",
    "STF.PA",
    "STMPA.PA",
    "TKTT.PA",
    "TIT.MI",
    "TEP.PA",
    "TFI.PA",
    "HO.PA",
    "TKO.PA",
    "TTE.PA",
    "TNG.PA",
    "TRI.PA",
    "UBI.PA",
    "UCG.MI",
    "URW.PA",
    "FR.PA",
    "VK.PA",
    "VLA.PA",
    "VIE.PA",
    "VRLA.PA",
    "VMX.PA",
    "VETO.PA",
    "VCT.PA",
    "DG.PA",
    "VIRP.PA",
    "VIV.PA",
    "VLTSA.PA",
    "WAVE.PA",
    "MF.PA",
    "WLN.PA",
    "XFAB.PA",
    "AL2SI.PA",
]